name: Reusable Microservice Test/Build/Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: 'dev'
      namespace:
        description: 'Kubernetes namespace'
        required: true
        type: string
        default: 'developer'
      ecr-registry:
        description: 'ECR registry URL'
        required: false
        type: string
        default: 'kubeclever'
      subdir:
        description: 'Subdirectory containing the microservice'
        required: false
        type: string
        default: '.'
      language:
        description: 'Programming language of the microservice'
        required: true
        type: string
        default: 'golang'
      go-version:
        description: 'Go version'
        required: false
        type: string
        default: '1.21'
      run-snyk-scan:
        description: 'Run Snyk scan'
        required: false
        type: boolean
        default: false
      dockerhub-username:
        description: 'Docker Hub username'
        required: true
        type: string
      run-e2e-test:
        description: 'Run E2E tests'
        required: false
        type: boolean
        default: false
      run-code-coverage:
        description: 'Run code coverage'
        required: false
        type: boolean
        default: false
    secrets:
      base-workflows-gh-token:
        description: 'GitHub token for accessing base workflows'
        required: false
      twistlock-secret-key:
        description: 'Twistlock secret key'
        required: true
      snyk-token:
        description: Snyk token used for uploading Docker image scan results to Snyk.
        required: false
      dockerhub-password:
        description: Docker Hub password
        required: true
      # TODO: Add more secrets as needed


defaults:
  run:
    shell: bash

env: {}

permissions:
  id-token: write
  contents: write
  issues: write
  actions: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: echo "Preparing environment..."
      - name: Get Reusable Workflow params via OIDC ID token because they're not otherwise exposed
        id: id-token
        uses: ChristopherHX/oidc@v3
      - name: Checkout repository to be able to invoke actions & scripts
        uses: actions/checkout@v6
        with:  # Required for checkout action to work around when workflow called from other repo.
            repository: ${{ steps.id-token.outputs.job_workflow_repo_name_and_owner }}
            ref: ${{ steps.id-token.outputs.job_workflow_sha }}
            token: ${{ secrets.base-workflows-gh-token || github.token }}
      - name: Checkout caller repository ${{ github.repository }}
        uses: actions/checkout@v6
        with:
            path: caller-repo
      - name: Compute and expose values
        id: values
        working-directory: caller-repo/${{ inputs.subdir }}/helm
        run: |
            full_repo_name="${{ github.repository }}"
            repo_name="$(cut -d/ -f2 <<< "$full_repo_name")"
            chart_url="oci://${{ inputs.ecr-registry }}/${repo_name}-chart"
            chart_name="$(echo "$chart_url" | rev | cut -d/ -f1 | rev)"
            chart_version=$(yq -r .version Chart.yaml)
            app_version=$(yq -r .appVersion Chart.yaml)
            image_name="${{ inputs.ecr-registry }}/${repo_name}"
            image_tag=$app_version

            # Expose as github outputs:
            tee -a "$GITHUB_OUTPUT" <<EOF
            repo-name=$repo_name
            chart-name=$chart_name
            chart-version=$chart_version
            app-version=$app_version
            image-name=$image_name
            image-tag=$app_version
            image=$image_name:$image_tag
            EOF
      - name: Print to summary
        run: |
            tee -a "$GITHUB_STEP_SUMMARY" <<'EOF'
            - Repo name: `${{ steps.values.outputs.repo-name }}`
            - Subdir: ${{ inputs.subdir && format('`{0}`', inputs.subdir) || 'N/A' }}
            - Chart name: `${{ steps.values.outputs.chart-name }}`
            - Chart version: `${{ steps.values.outputs.chart-version }}`
            - App version: `${{ steps.values.outputs.app-version }}`
            - Chart URL: `${{ steps.values.outputs.chart-url }}`
            EOF
            if [ "${{ inputs.docker-skip-build }}" = "false" ]; then
            echo '- Docker image: `${{ steps.values.outputs.image }}`' | tee -a "$GITHUB_STEP_SUMMARY"
            fi
      - name: Check if version is bumped
        if: inputs.fail-if-pr-not-version-bumped == true && github.event_name == 'pull_request'
        working-directory: caller-repo/${{ inputs.subdir }}/helm
        run: |
            if ! ${{ github.workspace }}/.github/scripts/check-chart-version.sh \
            . ${{ github.head_ref }} ${{ github.base_ref }}
            then
            echo "❌ ERROR: Chart version is not bumped." | tee -a "$GITHUB_STEP_SUMMARY"
            exit 1
            fi
    outputs:
      repo-name: ${{ steps.values.outputs.repo-name }}
      chart-name: ${{ steps.values.outputs.chart-name }}
      chart-version: ${{ steps.values.outputs.chart-version }}
      app-version: ${{ steps.values.outputs.app-version }}
      image-name: ${{ steps.values.outputs.image-name }}
      image-tag: ${{ steps.values.outputs.image-tag }}
      image: ${{ steps.values.outputs.image }}
      

  lint:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Run Go Lint
        run: echo "Linting..."

  e2e-test:
    runs-on: ubuntu-latest
    needs: [prepare]
    if: inputs.run-e2e-test == true
    steps:
      - name: Run E2E Tests
        run: echo "Running E2E Tests..."

  code-coverage:
    runs-on: ubuntu-latest
    needs: [prepare]
    if: inputs.run-code-coverage == true
    steps:
      - name: Run Code Coverage Checks
        run: echo "Running Code Coverage Checks..."

  build:
    runs-on: ubuntu-latest
    needs: [prepare, lint, e2e-test, code-coverage]
    steps:
      - name: Get Reusable Workflow params via OIDC ID token because they're not otherwise exposed
        id: id-token
        uses: ChristopherHX/oidc@v3
      - name: Checkout repository to be able to invoke actions & scripts
        uses: actions/checkout@v6
        with:  # Required for checkout action to work around when workflow called from other repo.
          repository: ${{ steps.id-token.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.id-token.outputs.job_workflow_sha }}
          token: ${{ secrets.base-workflows-gh-token || github.token }}
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          cache: false
      - name: Checkout caller repository ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          path: caller-repo
      - name: Build docker image
        working-directory: caller-repo/${{ inputs.subdir }}
        run: |
            docker build -t ${{ needs.prepare.outputs.image }} .
      - name: Push docker image
        run: echo "Pushing docker image..."

  twistlock-scan:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Run Twistlock Scan
        run: echo "Running Twistlock Scan..."

  snyk-scan:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Run Snyk Scan
        run: echo "Running Snyk Scan..."

  build-helm-chart:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Get Reusable Workflow params via OIDC ID token because they're not otherwise exposed
        id: id-token
        uses: ChristopherHX/oidc@v3
      - name: Checkout repository to be able to invoke actions & scripts
        uses: actions/checkout@v6
        with:  # Required for checkout action to work around when workflow called from other repo.
            repository: ${{ steps.id-token.outputs.job_workflow_repo_name_and_owner }}
            ref: ${{ steps.id-token.outputs.job_workflow_sha }}
            token: ${{ secrets.base-workflows-gh-token || github.token }}
      - name: Checkout caller repository ${{ github.repository }}
        uses: actions/checkout@v6
        with:
            path: caller-repo
      - name: Helm Package
        id: package
        working-directory: caller-repo/${{ inputs.subdir }}
        run: |
            helm package \
            --dependency-update \
            --version ${{ needs.prepare.outputs.chart-version }} \
            --app-version ${{ needs.prepare.outputs.app-version }} \
            ./helm
            PACKAGE_FILENAME="${{ needs.prepare.outputs.chart-name }}-${{ needs.prepare.outputs.chart-version }}.tgz"
            echo "Packaged successfully. Package name is $PACKAGE_FILENAME"
            echo "Package contents:"
            tar -tzf "$PACKAGE_FILENAME" | sort
            echo "filename=$PACKAGE_FILENAME" >> "$GITHUB_OUTPUT"
            echo "artifact=${{ needs.prepare.outputs.chart-name }}-${{ needs.prepare.outputs.chart-version }}" >> "$GITHUB_OUTPUT"
            echo ":tada: **Packaged successfully!** :tada:" | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Helm Login
        run: echo "Helm Login..."
      - name: Helm Push
        run: echo "Helm Push..."

  deploy:
    runs-on: ubuntu-latest
    needs: [prepare, build-helm-chart]
    steps:
      - name: Get Reusable Workflow params via OIDC ID token because they're not otherwise exposed
        id: id-token
        uses: ChristopherHX/oidc@v3
      - name: Checkout repository to be able to invoke actions & scripts
        uses: actions/checkout@v6
        with:  # Required for checkout action to work around when workflow called from other repo.
            repository: ${{ steps.id-token.outputs.job_workflow_repo_name_and_owner }}
            ref: ${{ steps.id-token.outputs.job_workflow_sha }}
            token: ${{ secrets.base-workflows-gh-token || github.token }}
      - name: Checkout caller repository ${{ github.repository }}
        uses: actions/checkout@v6
        with:
            path: caller-repo
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes..."
          helm upgrade --install ${{ needs.prepare.outputs.chart-name }} ${{ needs.prepare.outputs.chart-name }} \
          -n ${{ inputs.namespace }} \
          --dry-run \
          --wait --timeout 3600
          echo -e "\n✅ **Successfully deployed helm chart!** :tada:" | tee -a "$GITHUB_STEP_SUMMARY"


